### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bettybhzhou** [UBC-MDS/Crime_Data#20]
Pros:
- easy to use and navigate through the app.

Improvements:
- it was confusing that widgets that wasn't related to the visualization of the tabs were present. Maybe only show the related widgets for each tab.
- It was hard to differentiate different crime density. Maybe include density values to make it more explicit.
- Change density colour between each crime on the map tab.

Bugs:

- interactivity of the slider and drop down menu are not fully implemented. For example, changing the city does not change the map visualization.
- interpretability of the single city tab is ambiguous. For example, I was unsure of what the histogram represents on this graph.

**Comment by aylapear** [comment]
Thank you bettybhzhou  for your feedback on our app. We have made some improvements based on your suggestions. 
- The widgets that didn't control anything on the tabs have been removed (ie removing the city drop down on the map tab and the year slider on the single city tab)
- We are going to change the colors of density circles for each crime
- on the single city tab we have changed the crime type to be check-boxes which helps people see when they select population it draws the bars underneath it. We wanted population to have a different style then the crime rates.
