### ISSUE TITLE
Review from Weifeng Guo and Rezabagheri

### ISSUE THREAD

**Issue by DavyGuo** [UBC-MDS/Crime_Data#21]
Fly on the wall: 

-  The layout is reasonable, very straightforward, the map view is really clear. Moving the cursor to the point could show the city name.
- The slide bar is a little confusing,  didn't know  whether it means a specific year or a time range
- Under the map view, select a city doesn't bring any change.
- Under the single city view, change the slide bar will bring change only to the table, select the city will bring change to both plot and table.
- Very easy to understand. 

Informed Run:

- Confirmed that under the map tab, select a city  doesn't bring any change to the map view.
- Confirmed that under the single tab view, change crime type won't bring any change.

Written + Oral feedback:

Overall, this app is very friendly to understand and use. The map view is great to display the national data. The size of the scatter related to the data is very smart. The single city tab show detailed information of a selected city, which data were displayed very well.

There are still some minor part this app may improve:

- For the slide bar, the display may make user think it represent a time range while it actually means a specific year. The developer may change the display of the slide bar to dropout menu.
- Under the map tab, moving cursor to the scatter only display the info of the city name. The user may want to know more about the detailed the information like population and crime rate. The developer may consider about adding it to the code.
- For the single city tab, the default display is blank, the developer may consider add an initial chart or display.

**Comment by aylapear** [comment]
Thank you for the feedback DavyGuo. 
- Updated the slide of the slide bar so it doesn't look to be a time range
- Updated the tool tip to display to display the values for the city along with the city name
- The single city tab now has the first city automatically selected so it displays a chart when the user clicks on the tab
