### ISSUE TITLE
JPushor Milestone3 Feedback

### ISSUE THREAD

**Issue by jpush1773** [UBC-MDS/Crime_Data#24]
Overall, great job.

Positive Feedback:

- Found explanation of use case to be clear and very applicable.
- The app is clean and free of "cluster".
- Loved the national map and then the ability to get specific data about a city. Very applicable to someone working in government.

Consider:

- Adding a bit of text to be used for orientation for a new or infrequent user.
- Adding a title to the plots to assist in orientation and purpose.
- Increasing the size of font on x and y-ticks
- Adding some detail when you click on the city in "map-view". I.e. The user clicks on Seattle and sees a few key summary statistics.
- In the table below the "Single City" tab, add cities that are considered comparables. I.e. Houston vs Dallas, Chicago vs New York, San Diego vs San Francisco. Maybe easier to include cities in the same state, or by population size.

**Comment by aylapear** [comment]
Thanks JPushor for feedback on our app. We implemented some of these changes in the newest version of our app like adding a Help tab to orientate new users, increasing font sizes and adding a hover function to the circles on the map tab.
